defaults:
- _self_


num_frames: 90
num_coords: 3


experiment:
  name: SimpleCNN2D
  output_dir: /path/to/output/
  log_file: /path/to/output/SimpleCNN2D.log

hydra:
  run:
    dir: "${experiment.output_dir}/hydra/${experiment.name}"

dataset:
  name: cnn
  dataset_dir: /path/to/sign_language_videos/popsign_v2/563/mediapipe/normalized
  label_file: /path/to/PopSignV2-ML/ml-pipeline/metadata/563_sign_list.txt
  num_frames: ${num_frames}
  num_coords: ${num_coords}
  padding: default

dataloader:
  batch_size: 256
  shuffle: false
  num_workers: 16

model:
  name: SCNN2D
  save_name: SCNN2D
  num_features: 21
  num_frames: ${num_frames}
  num_coords: ${num_coords}
  num_signs: 563

training:
  optimizer: adam
  learning_rate: 0.001
  alpha: 0.9
  num_epochs: 50




